// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkAEr_Jv0wWxF997KLZc53AJxoXZV9Yg',
    appId: '1:1052142196284:web:c2d759a052ebc141a01539',
    messagingSenderId: '1052142196284',
    projectId: 'food-order-app-3850e',
    authDomain: 'food-order-app-3850e.firebaseapp.com',
    storageBucket: 'food-order-app-3850e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxRfQLW5U1fmLg_V-2jpXwcLfUys5EMc',
    appId: '1:1052142196284:android:7b0518b933b14817a01539',
    messagingSenderId: '1052142196284',
    projectId: 'food-order-app-3850e',
    storageBucket: 'food-order-app-3850e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzWovO480_6KvJ6P-MT8tMXo2FTbvalU',
    appId: '1:1052142196284:ios:4337f5f46badb63da01539',
    messagingSenderId: '1052142196284',
    projectId: 'food-order-app-3850e',
    storageBucket: 'food-order-app-3850e.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzWovO480_6KvJ6P-MT8tMXo2FTbvalU',
    appId: '1:1052142196284:ios:4337f5f46badb63da01539',
    messagingSenderId: '1052142196284',
    projectId: 'food-order-app-3850e',
    storageBucket: 'food-order-app-3850e.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXkAEr_Jv0wWxF997KLZc53AJxoXZV9Yg',
    appId: '1:1052142196284:web:be9c765b1d5ab7f5a01539',
    messagingSenderId: '1052142196284',
    projectId: 'food-order-app-3850e',
    authDomain: 'food-order-app-3850e.firebaseapp.com',
    storageBucket: 'food-order-app-3850e.firebasestorage.app',
  );
}
